// 单词库和对应的图片（emoji）- 动物、鱼类、植物

const wordData = {
  easy: [
    { word: 'cat', emoji: '🐱' },
    { word: 'dog', emoji: '🐶' },
    { word: 'bird', emoji: '🐦' },
    { word: 'fish', emoji: '🐟' },
    { word: 'cow', emoji: '🐄' },
    { word: 'pig', emoji: '🐷' },
    { word: 'duck', emoji: '🦆' },
    { word: 'bee', emoji: '🐝' },
    { word: 'ant', emoji: '🐜' },
    { word: 'owl', emoji: '🦉' },
    { word: 'fox', emoji: '🦊' },
    { word: 'bear', emoji: '🐻' },
    { word: 'lion', emoji: '🦁' },
    { word: 'tiger', emoji: '🐯' },
    { word: 'rat', emoji: '🐀' },
    { word: 'mouse', emoji: '🐭' },
    { word: 'hamster', emoji: '🐹' },
    { word: 'rabbit', emoji: '🐰' },
    { word: 'bat', emoji: '🦇' },
    { word: 'deer', emoji: '🦌' },
    { word: 'tree', emoji: '🌳' },
    { word: 'rose', emoji: '🌹' },
    { word: 'leaf', emoji: '🍃' },
    { word: 'seed', emoji: '🌱' },
    { word: 'mushroom', emoji: '🍄' },
    { word: 'sunflower', emoji: '🌻' },
    { word: 'grass', emoji: '🌾' },
    { word: 'flower', emoji: '🌺' },
    { word: 'bud', emoji: '🌷' },
    { word: 'bamboo', emoji: '🎋' },
    { word: 'clover', emoji: '🍀' },
    { word: 'maple', emoji: '🍁' },
    { word: 'tuna', emoji: '🐟' },
    { word: 'salmon', emoji: '🐟' },
    { word: 'carp', emoji: '🐟' },
    { word: 'eel', emoji: '🐍' },
    { word: 'pike', emoji: '🐟' }
  ],
  medium: [
    { word: 'panda', emoji: '🐼' },
    { word: 'koala', emoji: '🐨' },
    { word: 'penguin', emoji: '🐧' },
    { word: 'dolphin', emoji: '🐬' },
    { word: 'whale', emoji: '🐋' },
    { word: 'shark', emoji: '🦈' },
    { word: 'octopus', emoji: '🐙' },
    { word: 'turtle', emoji: '🐢' },
    { word: 'frog', emoji: '🐸' },
    { word: 'butterfly', emoji: '🦋' },
    { word: 'snail', emoji: '🐌' },
    { word: 'spider', emoji: '🕷️' },
    { word: 'ladybug', emoji: '🐞' },
    { word: 'elephant', emoji: '🐘' },
    { word: 'giraffe', emoji: '🦒' },
    { word: 'zebra', emoji: '🦓' },
    { word: 'monkey', emoji: '🐵' },
    { word: 'chicken', emoji: '🐔' },
    { word: 'horse', emoji: '🐴' },
    { word: 'sheep', emoji: '🐑' },
    { word: 'goat', emoji: '🐐' },
    { word: 'camel', emoji: '🐫' },
    { word: 'llama', emoji: '🦙' },
    { word: 'turkey', emoji: '🦃' },
    { word: 'rooster', emoji: '🐓' },
    { word: 'peacock', emoji: '🦚' },
    { word: 'parrot', emoji: '🦜' },
    { word: 'flamingo', emoji: '🦩' },
    { word: 'swan', emoji: '🦢' },
    { word: 'eagle', emoji: '🦅' },
    { word: 'hawk', emoji: '🦅' },
    { word: 'crow', emoji: '🐦‍⬛' },
    { word: 'dove', emoji: '🕊️' },
    { word: 'seal', emoji: '🦭' },
    { word: 'walrus', emoji: '🦭' },
    { word: 'otter', emoji: '🦦' },
    { word: 'beaver', emoji: '🦫' },
    { word: 'hedgehog', emoji: '🦔' },
    { word: 'raccoon', emoji: '🦝' },
    { word: 'skunk', emoji: '🦨' },
    { word: 'badger', emoji: '🦡' },
    { word: 'mole', emoji: '🦫' },
    { word: 'squirrel', emoji: '🐿️' },
    { word: 'chipmunk', emoji: '🐿️' },
    { word: 'apple', emoji: '🍎' },
    { word: 'banana', emoji: '🍌' },
    { word: 'orange', emoji: '🍊' },
    { word: 'grape', emoji: '🍇' },
    { word: 'strawberry', emoji: '🍓' },
    { word: 'watermelon', emoji: '🍉' },
    { word: 'pineapple', emoji: '🍍' },
    { word: 'cherry', emoji: '🍒' },
    { word: 'peach', emoji: '🍑' },
    { word: 'mango', emoji: '🥭' },
    { word: 'coconut', emoji: '🥥' },
    { word: 'avocado', emoji: '🥑' },
    { word: 'tomato', emoji: '🍅' },
    { word: 'carrot', emoji: '🥕' },
    { word: 'corn', emoji: '🌽' },
    { word: 'pepper', emoji: '🌶️' },
    { word: 'cucumber', emoji: '🥒' },
    { word: 'broccoli', emoji: '🥦' },
    { word: 'lettuce', emoji: '🥬' },
    { word: 'cabbage', emoji: '🥬' },
    { word: 'onion', emoji: '🧅' },
    { word: 'potato', emoji: '🥔' },
    { word: 'eggplant', emoji: '🍆' },
    { word: 'peas', emoji: '🫛' },
    { word: 'beans', emoji: '🫘' },
    { word: 'peanut', emoji: '🥜' },
    { word: 'almond', emoji: '🥜' },
    { word: 'walnut', emoji: '🥜' },
    { word: 'chestnut', emoji: '🌰' },
    { word: 'kiwi', emoji: '🥝' },
    { word: 'blueberry', emoji: '🫐' },
    { word: 'raspberry', emoji: '🫐' },
    { word: 'blackberry', emoji: '🫐' },
    { word: 'cactus', emoji: '🌵' },
    { word: 'palm tree', emoji: '🌴' },
    { word: 'evergreen', emoji: '🌲' },
    { word: 'cherry blossom', emoji: '🌸' },
    { word: 'tulip', emoji: '🌷' },
    { word: 'hibiscus', emoji: '🌺' },
    { word: 'lotus', emoji: '🪷' },
    { word: 'bouquet', emoji: '💐' },
    { word: 'herb', emoji: '🌿' },
    { word: 'clover', emoji: '🍀' },
    { word: 'maple leaf', emoji: '🍁' },
    { word: 'fallen leaf', emoji: '🍂' },
    { word: 'potted plant', emoji: '🪴' },
    { word: 'seedling', emoji: '🌱' },
    { word: 'jellyfish', emoji: '🎐' },
    { word: 'seahorse', emoji: '🐴' },
    { word: 'stingray', emoji: '🐟' },
    { word: 'pufferfish', emoji: '🐡' },
    { word: 'angelfish', emoji: '🐟' },
    { word: 'goldfish', emoji: '🐠' },
    { word: 'tropical fish', emoji: '🐠' },
    { word: 'lobster', emoji: '🦞' },
    { word: 'crab', emoji: '🦀' },
    { word: 'shrimp', emoji: '🦐' },
    { word: 'squid', emoji: '🦑' },
    { word: 'starfish', emoji: '⭐' },
    { word: 'sea urchin', emoji: '🌊' },
    { word: 'coral', emoji: '🪸' },
    { word: 'seaweed', emoji: '🌊' }
  ],
  hard: [
    { word: 'alligator', emoji: '🐊' },
    { word: 'crocodile', emoji: '🐊' },
    { word: 'hippopotamus', emoji: '🦛' },
    { word: 'rhinoceros', emoji: '🦏' },
    { word: 'kangaroo', emoji: '🦘' },
    { word: 'wombat', emoji: '🦘' },
    { word: 'platypus', emoji: '🦫' },
    { word: 'koala bear', emoji: '🐨' },
    { word: 'panda bear', emoji: '🐼' },
    { word: 'polar bear', emoji: '🐻‍❄️' },
    { word: 'grizzly bear', emoji: '🐻' },
    { word: 'black bear', emoji: '🐻' },
    { word: 'brown bear', emoji: '🐻' },
    { word: 'leopard', emoji: '🐆' },
    { word: 'cheetah', emoji: '🐆' },
    { word: 'jaguar', emoji: '🐆' },
    { word: 'panther', emoji: '🐆' },
    { word: 'lynx', emoji: '🐱' },
    { word: 'bobcat', emoji: '🐱' },
    { word: 'cougar', emoji: '🐱' },
    { word: 'wolf', emoji: '🐺' },
    { word: 'coyote', emoji: '🐺' },
    { word: 'hyena', emoji: '🦓' },
    { word: 'jackal', emoji: '🐺' },
    { word: 'dingo', emoji: '🐕' },
    { word: 'wild boar', emoji: '🐗' },
    { word: 'warthog', emoji: '🐗' },
    { word: 'bison', emoji: '🦬' },
    { word: 'buffalo', emoji: '🦬' },
    { word: 'yak', emoji: '🐂' },
    { word: 'musk ox', emoji: '🦬' },
    { word: 'moose', emoji: '🦌' },
    { word: 'elk', emoji: '🦌' },
    { word: 'reindeer', emoji: '🦌' },
    { word: 'caribou', emoji: '🦌' },
    { word: 'antelope', emoji: '🦌' },
    { word: 'gazelle', emoji: '🦌' },
    { word: 'impala', emoji: '🦌' },
    { word: 'wildebeest', emoji: '🦬' },
    { word: 'gnu', emoji: '🦬' },
    { word: 'okapi', emoji: '🦒' },
    { word: 'tapir', emoji: '🦏' },
    { word: 'armadillo', emoji: '🦔' },
    { word: 'pangolin', emoji: '🦔' },
    { word: 'sloth', emoji: '🦥' },
    { word: 'anteater', emoji: '🦏' },
    { word: 'aardvark', emoji: '🦏' },
    { word: 'meerkat', emoji: '🐱' },
    { word: 'mongoose', emoji: '🐱' },
    { word: 'ferret', emoji: '🐱' },
    { word: 'weasel', emoji: '🐱' },
    { word: 'mink', emoji: '🐱' },
    { word: 'stoat', emoji: '🐱' },
    { word: 'otter', emoji: '🦦' },
    { word: 'sea otter', emoji: '🦦' },
    { word: 'river otter', emoji: '🦦' },
    { word: 'beaver', emoji: '🦫' },
    { word: 'muskrat', emoji: '🦫' },
    { word: 'porcupine', emoji: '🦔' },
    { word: 'chinchilla', emoji: '🐹' },
    { word: 'guinea pig', emoji: '🐹' },
    { word: 'capybara', emoji: '🐹' },
    { word: 'lemur', emoji: '🐵' },
    { word: 'baboon', emoji: '🐵' },
    { word: 'macaque', emoji: '🐵' },
    { word: 'orangutan', emoji: '🦧' },
    { word: 'gorilla', emoji: '🦍' },
    { word: 'chimpanzee', emoji: '🐵' },
    { word: 'bonobo', emoji: '🐵' },
    { word: 'gibbon', emoji: '🐵' },
    { word: 'mandrill', emoji: '🐵' },
    { word: 'toucan', emoji: '🦜' },
    { word: 'cockatoo', emoji: '🦜' },
    { word: 'macaw', emoji: '🦜' },
    { word: 'hummingbird', emoji: '🐦' },
    { word: 'woodpecker', emoji: '🐦' },
    { word: 'kingfisher', emoji: '🐦' },
    { word: 'heron', emoji: '🦢' },
    { word: 'crane', emoji: '🦢' },
    { word: 'stork', emoji: '🦩' },
    { word: 'ibis', emoji: '🦩' },
    { word: 'pelican', emoji: '🦢' },
    { word: 'albatross', emoji: '🦅' },
    { word: 'seagull', emoji: '🦅' },
    { word: 'puffin', emoji: '🐧' },
    { word: 'auk', emoji: '🐧' },
    { word: 'cormorant', emoji: '🦅' },
    { word: 'gannet', emoji: '🦅' },
    { word: 'frigatebird', emoji: '🦅' },
    { word: 'tropicbird', emoji: '🦅' },
    { word: 'booby', emoji: '🦅' },
    { word: 'anaconda', emoji: '🐍' },
    { word: 'python', emoji: '🐍' },
    { word: 'boa constrictor', emoji: '🐍' },
    { word: 'cobra', emoji: '🐍' },
    { word: 'viper', emoji: '🐍' },
    { word: 'rattlesnake', emoji: '🐍' },
    { word: 'mamba', emoji: '🐍' },
    { word: 'taipan', emoji: '🐍' },
    { word: 'sea snake', emoji: '🐍' },
    { word: 'komodo dragon', emoji: '🦎' },
    { word: 'iguana', emoji: '🦎' },
    { word: 'chameleon', emoji: '🦎' },
    { word: 'gecko', emoji: '🦎' },
    { word: 'salamander', emoji: '🦎' },
    { word: 'newt', emoji: '🦎' },
    { word: 'axolotl', emoji: '🦎' },
    { word: 'caecilian', emoji: '🦎' },
    { word: 'mantis shrimp', emoji: '🦐' },
    { word: 'hermit crab', emoji: '🦀' },
    { word: 'fiddler crab', emoji: '🦀' },
    { word: 'spider crab', emoji: '🦀' },
    { word: 'king crab', emoji: '🦀' },
    { word: 'snow crab', emoji: '🦀' },
    { word: 'blue crab', emoji: '🦀' },
    { word: 'dungeness crab', emoji: '🦀' },
    { word: 'stonefish', emoji: '🐡' },
    { word: 'lionfish', emoji: '🐡' },
    { word: 'scorpionfish', emoji: '🐡' },
    { word: 'triggerfish', emoji: '🐡' },
    { word: 'butterflyfish', emoji: '🐠' },
    { word: 'angelfish', emoji: '🐠' },
    { word: 'surgeonfish', emoji: '🐠' },
    { word: 'tang', emoji: '🐠' },
    { word: 'clownfish', emoji: '🐠' },
    { word: 'damselfish', emoji: '🐠' },
    { word: 'wrasse', emoji: '🐠' },
    { word: 'parrotfish', emoji: '🐠' },
    { word: 'grouper', emoji: '🐟' },
    { word: 'snapper', emoji: '🐟' },
    { word: 'bass', emoji: '🐟' },
    { word: 'perch', emoji: '🐟' },
    { word: 'pike', emoji: '🐟' },
    { word: 'marlin', emoji: '🐟' },
    { word: 'sailfish', emoji: '🐟' },
    { word: 'swordfish', emoji: '🐟' },
    { word: 'barracuda', emoji: '🐟' },
    { word: 'tuna', emoji: '🐟' },
    { word: 'mackerel', emoji: '🐟' },
    { word: 'sardine', emoji: '🐟' },
    { word: 'anchovy', emoji: '🐟' },
    { word: 'herring', emoji: '🐟' },
    { word: 'cod', emoji: '🐟' },
    { word: 'haddock', emoji: '🐟' },
    { word: 'pollock', emoji: '🐟' },
    { word: 'halibut', emoji: '🐟' },
    { word: 'flounder', emoji: '🐟' },
    { word: 'sole', emoji: '🐟' },
    { word: 'plaice', emoji: '🐟' },
    { word: 'turbot', emoji: '🐟' },
    { word: 'dragon fruit', emoji: '🐉' },
    { word: 'passion fruit', emoji: '🥭' },
    { word: 'guava', emoji: '🥭' },
    { word: 'papaya', emoji: '🥭' },
    { word: 'lychee', emoji: '🥭' },
    { word: 'rambutan', emoji: '🥭' },
    { word: 'durian', emoji: '🥭' },
    { word: 'jackfruit', emoji: '🥭' },
    { word: 'starfruit', emoji: '⭐' },
    { word: 'persimmon', emoji: '🍊' },
    { word: 'pomegranate', emoji: '🍎' },
    { word: 'fig', emoji: '🍇' },
    { word: 'date', emoji: '🌴' },
    { word: 'olive', emoji: '🫒' },
    { word: 'artichoke', emoji: '🥬' },
    { word: 'asparagus', emoji: '🥬' },
    { word: 'zucchini', emoji: '🥒' },
    { word: 'squash', emoji: '🥒' },
    { word: 'pumpkin', emoji: '🎃' },
    { word: 'gourd', emoji: '🥒' },
    { word: 'radish', emoji: '🥕' },
    { word: 'turnip', emoji: '🥕' },
    { word: 'beet', emoji: '🥕' },
    { word: 'rutabaga', emoji: '🥕' },
    { word: 'parsnip', emoji: '🥕' },
    { word: 'celery', emoji: '🥬' },
    { word: 'fennel', emoji: '🥬' },
    { word: 'leek', emoji: '🧅' },
    { word: 'shallot', emoji: '🧅' },
    { word: 'garlic', emoji: '🧄' },
    { word: 'ginger', emoji: '🫚' },
    { word: 'turmeric', emoji: '🫚' },
    { word: 'wasabi', emoji: '🌶️' },
    { word: 'horseradish', emoji: '🌶️' },
    { word: 'mustard', emoji: '🌶️' },
    { word: 'cauliflower', emoji: '🥦' },
    { word: 'brussels sprouts', emoji: '🥦' },
    { word: 'kale', emoji: '🥬' },
    { word: 'spinach', emoji: '🥬' },
    { word: 'arugula', emoji: '🥬' },
    { word: 'watercress', emoji: '🥬' },
    { word: 'bok choy', emoji: '🥬' },
    { word: 'chard', emoji: '🥬' },
    { word: 'collard greens', emoji: '🥬' },
    { word: 'endive', emoji: '🥬' },
    { word: 'escarole', emoji: '🥬' },
    { word: 'frisée', emoji: '🥬' },
    { word: 'radicchio', emoji: '🥬' },
    { word: 'mushroom', emoji: '🍄' },
    { word: 'shiitake', emoji: '🍄' },
    { word: 'portobello', emoji: '🍄' },
    { word: 'cremini', emoji: '🍄' },
    { word: 'oyster mushroom', emoji: '🍄' },
    { word: 'enoki', emoji: '🍄' },
    { word: 'maitake', emoji: '🍄' },
    { word: 'chanterelle', emoji: '🍄' },
    { word: 'morel', emoji: '🍄' },
    { word: 'truffle', emoji: '🍄' },
    { word: 'bamboo shoot', emoji: '🎋' },
    { word: 'lotus root', emoji: '🪷' },
    { word: 'water chestnut', emoji: '🌰' },
    { word: 'jicama', emoji: '🥕' },
    { word: 'daikon', emoji: '🥕' },
    { word: 'kohlrabi', emoji: '🥬' },
    { word: 'okra', emoji: '🥒' },
    { word: 'edamame', emoji: '🫛' },
    { word: 'lima beans', emoji: '🫘' },
    { word: 'black beans', emoji: '🫘' },
    { word: 'kidney beans', emoji: '🫘' },
    { word: 'navy beans', emoji: '🫘' },
    { word: 'pinto beans', emoji: '🫘' },
    { word: 'chickpeas', emoji: '🫘' },
    { word: 'lentils', emoji: '🫘' },
    { word: 'split peas', emoji: '🫘' },
    { word: 'black-eyed peas', emoji: '🫘' },
    { word: 'mung beans', emoji: '🫘' },
    { word: 'adzuki beans', emoji: '🫘' },
    { word: 'fava beans', emoji: '🫘' },
    { word: 'soybeans', emoji: '🫘' },
    { word: 'sunflower seeds', emoji: '🌻' },
    { word: 'pumpkin seeds', emoji: '🎃' },
    { word: 'sesame seeds', emoji: '🌾' },
    { word: 'poppy seeds', emoji: '🌾' },
    { word: 'chia seeds', emoji: '🌾' },
    { word: 'flax seeds', emoji: '🌾' },
    { word: 'hemp seeds', emoji: '🌾' },
    { word: 'quinoa', emoji: '🌾' },
    { word: 'amaranth', emoji: '🌾' },
    { word: 'buckwheat', emoji: '🌾' },
    { word: 'millet', emoji: '🌾' },
    { word: 'sorghum', emoji: '🌾' },
    { word: 'teff', emoji: '🌾' },
    { word: 'wild rice', emoji: '🌾' },
    { word: 'brown rice', emoji: '🌾' },
    { word: 'black rice', emoji: '🌾' },
    { word: 'red rice', emoji: '🌾' },
    { word: 'jasmine rice', emoji: '🌾' },
    { word: 'basmati rice', emoji: '🌾' },
    { word: 'arborio rice', emoji: '🌾' },
    { word: 'sushi rice', emoji: '🌾' },
    { word: 'sticky rice', emoji: '🌾' },
    { word: 'forbidden rice', emoji: '🌾' },
    { word: 'lotus flower', emoji: '🪷' },
    { word: 'water lily', emoji: '🪷' },
    { word: 'orchid', emoji: '🌺' },
    { word: 'daisy', emoji: '🌼' },
    { word: 'daffodil', emoji: '🌼' },
    { word: 'narcissus', emoji: '🌼' },
    { word: 'iris', emoji: '🌺' },
    { word: 'lily', emoji: '🌺' },
    { word: 'calla lily', emoji: '🌺' },
    { word: 'daylily', emoji: '🌺' },
    { word: 'tiger lily', emoji: '🌺' },
    { word: 'gladiolus', emoji: '🌺' },
    { word: 'freesia', emoji: '🌺' },
    { word: 'hyacinth', emoji: '🌺' },
    { word: 'crocus', emoji: '🌺' },
    { word: 'snowdrop', emoji: '🌼' },
    { word: 'bluebell', emoji: '🔔' },
    { word: 'lily of the valley', emoji: '🌺' },
    { word: 'peony', emoji: '🌺' },
    { word: 'ranunculus', emoji: '🌺' },
    { word: 'anemone', emoji: '🌺' },
    { word: 'poppy', emoji: '🌺' },
    { word: 'cosmos', emoji: '🌺' },
    { word: 'zinnia', emoji: '🌺' },
    { word: 'marigold', emoji: '🌼' },
    { word: 'petunia', emoji: '🌺' },
    { word: 'geranium', emoji: '🌺' },
    { word: 'begonia', emoji: '🌺' },
    { word: 'impatiens', emoji: '🌺' },
    { word: 'pansy', emoji: '🌺' },
    { word: 'viola', emoji: '🌺' },
    { word: 'snapdragon', emoji: '🌺' },
    { word: 'delphinium', emoji: '🌺' },
    { word: 'larkspur', emoji: '🌺' },
    { word: 'foxglove', emoji: '🌺' },
    { word: 'hollyhock', emoji: '🌺' },
    { word: 'lavender', emoji: '🪻' },
    { word: 'sage', emoji: '🌿' },
    { word: 'rosemary', emoji: '🌿' },
    { word: 'thyme', emoji: '🌿' },
    { word: 'oregano', emoji: '🌿' },
    { word: 'basil', emoji: '🌿' },
    { word: 'mint', emoji: '🌿' },
    { word: 'parsley', emoji: '🌿' },
    { word: 'cilantro', emoji: '🌿' },
    { word: 'dill', emoji: '🌿' },
    { word: 'chives', emoji: '🌿' },
    { word: 'tarragon', emoji: '🌿' },
    { word: 'marjoram', emoji: '🌿' },
    { word: 'bay leaf', emoji: '🌿' },
    { word: 'lemongrass', emoji: '🌿' },
    { word: 'kaffir lime', emoji: '🌿' },
    { word: 'curry leaf', emoji: '🌿' },
    { word: 'fenugreek', emoji: '🌿' },
    { word: 'cardamom', emoji: '🌿' },
    { word: 'cinnamon', emoji: '🌿' },
    { word: 'vanilla', emoji: '🌿' },
    { word: 'saffron', emoji: '🌿' },
    { word: 'star anise', emoji: '⭐' },
    { word: 'fennel seed', emoji: '🌿' },
    { word: 'cumin', emoji: '🌿' },
    { word: 'coriander', emoji: '🌿' },
    { word: 'caraway', emoji: '🌿' },
    { word: 'dill seed', emoji: '🌿' },
    { word: 'mustard seed', emoji: '🌿' },
    { word: 'nigella', emoji: '🌿' },
    { word: 'ajwain', emoji: '🌿' },
    { word: 'asafoetida', emoji: '🌿' },
    { word: 'sumac', emoji: '🌿' },
    { word: 'za\'atar', emoji: '🌿' },
    { word: 'berbere', emoji: '🌿' },
    { word: 'ras el hanout', emoji: '🌿' },
    { word: 'garam masala', emoji: '🌿' },
    { word: 'five spice', emoji: '⭐' },
    { word: 'seven spice', emoji: '⭐' },
    { word: 'chinese five spice', emoji: '⭐' },
    { word: 'japanese seven spice', emoji: '⭐' },
    { word: 'korean chili', emoji: '🌶️' },
    { word: 'thai chili', emoji: '🌶️' },
    { word: 'habanero', emoji: '🌶️' },
    { word: 'jalapeño', emoji: '🌶️' },
    { word: 'serrano', emoji: '🌶️' },
    { word: 'poblano', emoji: '🌶️' },
    { word: 'anaheim', emoji: '🌶️' },
    { word: 'cayenne', emoji: '🌶️' },
    { word: 'chipotle', emoji: '🌶️' },
    { word: 'paprika', emoji: '🌶️' },
    { word: 'pimento', emoji: '🌶️' },
    { word: 'bell pepper', emoji: '🫑' },
    { word: 'sweet pepper', emoji: '🫑' },
    { word: 'banana pepper', emoji: '🌶️' },
    { word: 'pepperoncini', emoji: '🌶️' },
    { word: 'peperoncino', emoji: '🌶️' },
    { word: 'calabrian chili', emoji: '🌶️' },
    { word: 'calabash', emoji: '🥒' },
    { word: 'bitter melon', emoji: '🥒' },
    { word: 'chayote', emoji: '🥒' },
    { word: 'luffa', emoji: '🥒' },
    { word: 'ridge gourd', emoji: '🥒' },
    { word: 'snake gourd', emoji: '🥒' },
    { word: 'ivy gourd', emoji: '🥒' },
    { word: 'tindora', emoji: '🥒' },
    { word: 'kundru', emoji: '🥒' },
    { word: 'parwal', emoji: '🥒' },
    { word: 'pointed gourd', emoji: '🥒' },
    { word: 'sponge gourd', emoji: '🥒' },
    { word: 'bottle gourd', emoji: '🥒' },
    { word: 'ash gourd', emoji: '🥒' },
    { word: 'winter melon', emoji: '🥒' },
    { word: 'wax gourd', emoji: '🥒' },
    { word: 'white gourd', emoji: '🥒' },
    { word: 'chinese winter melon', emoji: '🥒' },
    { word: 'dudhi', emoji: '🥒' },
    { word: 'lauki', emoji: '🥒' },
    { word: 'opo squash', emoji: '🥒' },
    { word: 'long melon', emoji: '🥒' },
    { word: 'calabaza', emoji: '🥒' },
    { word: 'west indian pumpkin', emoji: '🎃' },
    { word: 'turban squash', emoji: '🎃' },
    { word: 'butternut squash', emoji: '🎃' },
    { word: 'acorn squash', emoji: '🎃' },
    { word: 'delicata squash', emoji: '🎃' },
    { word: 'kabocha squash', emoji: '🎃' },
    { word: 'hubbard squash', emoji: '🎃' },
    { word: 'spaghetti squash', emoji: '🎃' },
    { word: 'pattypan squash', emoji: '🎃' },
    { word: 'yellow squash', emoji: '🎃' },
    { word: 'zucchini squash', emoji: '🥒' },
    { word: 'summer squash', emoji: '🥒' },
    { word: 'crookneck squash', emoji: '🥒' },
    { word: 'straightneck squash', emoji: '🥒' },
    { word: 'scallop squash', emoji: '🎃' },
    { word: 'sunburst squash', emoji: '🎃' },
    { word: 'eight ball squash', emoji: '🎃' },
    { word: 'round zucchini', emoji: '🥒' },
    { word: 'tromboncino', emoji: '🥒' },
    { word: 'trombetta', emoji: '🥒' },
    { word: 'zucchetta', emoji: '🥒' },
    { word: 'cucuzza', emoji: '🥒' },
    { word: 'italian squash', emoji: '🥒' },
    { word: 'serpent gourd', emoji: '🥒' },
    { word: 'snake gourd', emoji: '🥒' },
    { word: 'club gourd', emoji: '🥒' },
    { word: 'viper gourd', emoji: '🥒' },
    { word: 'trumpet gourd', emoji: '🥒' },
    { word: 'cucamelon', emoji: '🥒' },
    { word: 'mexican sour gherkin', emoji: '🥒' },
    { word: 'mouse melon', emoji: '🥒' },
    { word: 'mexican miniature watermelon', emoji: '🍉' },
    { word: 'pepquino', emoji: '🥒' },
    { word: 'sandita', emoji: '🍉' },
    { word: 'melon pear', emoji: '🍉' },
    { word: 'african horned cucumber', emoji: '🥒' },
    { word: 'kiwano', emoji: '🥒' },
    { word: 'horned melon', emoji: '🥒' },
    { word: 'jelly melon', emoji: '🥒' },
    { word: 'hedgehog melon', emoji: '🥒' },
    { word: 'cherry tomato', emoji: '🍅' },
    { word: 'grape tomato', emoji: '🍅' },
    { word: 'roma tomato', emoji: '🍅' },
    { word: 'beefsteak tomato', emoji: '🍅' }
  ]
};

// 获取单词列表（仅单词）
const getWordLists = () => {
  const lists = {};
  Object.keys(wordData).forEach(level => {
    lists[level] = wordData[level].map(item => item.word);
  });
  return lists;
};

// 根据单词获取 emoji
const getEmojiForWord = (word, level) => {
  const levelData = wordData[level] || wordData.easy;
  const item = levelData.find(item => item.word === word);
  return item ? item.emoji : '🌟'; // 默认返回星星
};

// 获取单词和 emoji 的完整信息
const getWordWithEmoji = (word, level) => {
  return {
    word: word,
    emoji: getEmojiForWord(word, level)
  };
};

module.exports = {
  wordData,
  getWordLists,
  getEmojiForWord,
  getWordWithEmoji
};

